#!/usr/bin/env bash
# Ternak TT — Path B fetcher.
#
# 1. git clone LSPosed/LSPlant + jmpews/Dobby into jni/
# 2. If javac + d8 are on PATH, compile java_helper/TernakHookHelper.java to
#    jni/helper_dex.h so java_hooks.cpp can embed the dex.
# 3. On CI (ubuntu-latest), javac is included in default-jdk; d8 comes from
#    Android SDK build-tools (setup by workflow).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
JNI="$ROOT/jni"

echo "==> Ternak TT — Path B lsplant fetcher"
echo "==> Root: $ROOT"

if ! command -v git >/dev/null 2>&1; then
    echo "!! git not found. Install git and re-run." >&2
    exit 1
fi

cd "$JNI"

if [ ! -d lsplant ]; then
    echo "==> Cloning LSPosed/LSPlant..."
    git clone --depth 1 --recurse-submodules https://github.com/LSPosed/LSPlant.git lsplant
else
    echo "==> lsplant already present"
fi

if [ ! -d dobby ]; then
    echo "==> Cloning jmpews/Dobby..."
    git clone --depth 1 --recurse-submodules https://github.com/jmpews/Dobby.git dobby
else
    echo "==> dobby already present"
fi

cd "$ROOT"

# ==== Compile helper Java -> dex -> embed as C header ====

HAS_JAVAC=0; HAS_D8=0
command -v javac >/dev/null 2>&1 && HAS_JAVAC=1
command -v d8    >/dev/null 2>&1 && HAS_D8=1

# Try to locate d8 in Android SDK if not on PATH (common on GitHub CI).
if [ "$HAS_D8" = "0" ] && [ -n "${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}" ]; then
    SDK="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}"
    D8_CAND=$(find "$SDK" -type f -name d8 2>/dev/null | head -1 || true)
    if [ -n "$D8_CAND" ]; then
        echo "==> Found d8 in SDK: $D8_CAND"
        export PATH="$(dirname "$D8_CAND"):$PATH"
        HAS_D8=1
    fi
fi

if [ -f java_helper/TernakHookHelper.java ] && [ "$HAS_JAVAC" = "1" ] && [ "$HAS_D8" = "1" ]; then
    echo "==> Compiling TernakHookHelper.java -> classes.dex -> jni/helper_dex.h"
    TMP="$(mktemp -d)"
    javac -source 8 -target 8 -d "$TMP" java_helper/TernakHookHelper.java
    # Package produces com/ternak/tt/*.class
    d8 --output "$TMP" $(find "$TMP" -name '*.class')
    if [ ! -f "$TMP/classes.dex" ]; then
        echo "!! d8 did not produce classes.dex — Path B helper dex not embedded"
    elif ! command -v xxd >/dev/null 2>&1; then
        echo "!! xxd not found — Path B helper dex not embedded"
    else
        {
            echo "// Auto-generated by fetch_lsplant.sh — do not edit."
            xxd -i -n HELPER_DEX "$TMP/classes.dex"
            echo "static const size_t HELPER_DEX_LEN = HELPER_DEX_len;"
            echo "#define TT_HAVE_HELPER_DEX 1"
        } > "$JNI/helper_dex.h"
        echo "==> Generated jni/helper_dex.h ($(wc -c <"$TMP/classes.dex") bytes)"
    fi
    rm -rf "$TMP"
else
    echo "!! javac/d8 or java_helper/ missing — Path B compiled but hook install will fail-soft"
    echo "   (HAS_JAVAC=$HAS_JAVAC HAS_D8=$HAS_D8)"
fi

echo ""
echo "==> Done. Now run: ./build.sh"
